package models

func catalogModels() []Model {
	return []Model{
		{
			ID:               "phi-4-mini",
			Name:             "Phi-4 Mini",
			Provider:         "Microsoft",
			Description:      "Small, capable model. Strong at reasoning, coding, and math.",
			SizeBytes:        2_100_000_000,
			Parameters:       "3.8B",
			Tags:             []string{"Reasoning", "Coding", "Math"},
			DownloadURL:      "https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf",
			Filename:         "microsoft_Phi-4-mini-instruct-Q4_K_M.gguf",
			MinRamGB:         3.0,
			RecommendedRamGB: 5.0,
			Capabilities:     []string{"reasoning", "coding", "math", "logic"},
			SpeedClass:       SpeedFast,
		},
		{
			ID:               "phi-3.1-mini",
			Name:             "Phi-3.1 Mini",
			Provider:         "Microsoft",
			Description:      "Excellent small model for chat and general tasks on mobile.",
			SizeBytes:        2_500_000_000,
			Parameters:       "3.8B",
			Tags:             []string{"Chat", "General", "Mobile"},
			DownloadURL:      "https://huggingface.co/bartowski/Phi-3.1-mini-4k-instruct-GGUF/resolve/main/Phi-3.1-mini-4k-instruct-Q4_K_M.gguf",
			Filename:         "Phi-3.1-mini-4k-instruct-Q4_K_M.gguf",
			MinRamGB:         3.0,
			RecommendedRamGB: 5.0,
			Capabilities:     []string{"chat", "general", "reasoning"},
			SpeedClass:       SpeedFast,
		},
		{
			ID:               "llama-3.2-3b",
			Name:             "Llama 3.2 3B",
			Provider:         "Meta",
			Description:      "Optimized for mobile and edge devices. Well-balanced chat and general tasks.",
			SizeBytes:        2_500_000_000,
			Parameters:       "3B",
			Tags:             []string{"Balanced", "Chat", "General"},
			DownloadURL:      "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
			Filename:         "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
			MinRamGB:         4.0,
			RecommendedRamGB: 6.0,
			Capabilities:     []string{"chat", "general", "creative"},
			SpeedClass:       SpeedMedium,
		},
		{
			ID:               "qwen-2.5-3b",
			Name:             "Qwen 2.5 3B",
			Provider:         "Alibaba",
			Description:      "High performance multilingual model with strong coding abilities.",
			SizeBytes:        3_100_000_000,
			Parameters:       "3B",
			Tags:             []string{"Multilingual", "Coding"},
			DownloadURL:      "https://huggingface.co/bartowski/Qwen2.5-3B-Instruct-GGUF/resolve/main/Qwen2.5-3B-Instruct-Q4_K_M.gguf",
			Filename:         "Qwen2.5-3B-Instruct-Q4_K_M.gguf",
			MinRamGB:         4.0,
			RecommendedRamGB: 6.0,
			Capabilities:     []string{"multilingual", "coding", "translation"},
			SpeedClass:       SpeedMedium,
		},
	}
}
