package models

func catalogModels() []Model {
	return []Model{
		{
			ID:               "gemma-3-4b",
			Name:             "Gemma 3 4B",
			Provider:         "Google",
			Description:      "Lightweight, state-of-the-art open model from Google. Excels at reasoning and chat.",
			SizeBytes:        2_800_000_000,
			Parameters:       "4B",
			Tags:             []string{"General", "Efficient", "Chat"},
			DownloadURL:      "https://huggingface.co/google/gemma-3-4b-it-gguf/resolve/main/gemma-3-4b-it-Q4_K_M.gguf",
			Filename:         "gemma-3-4b-it-Q4_K_M.gguf",
			ChecksumSHA256:   "",
			MinRamGB:         4.0,
			RecommendedRamGB: 6.0,
			Capabilities:     []string{"chat", "reasoning", "summarization"},
			SpeedClass:       SpeedFast,
		},
		{
			ID:               "phi-4-mini",
			Name:             "Phi-4 Mini",
			Provider:         "Microsoft",
			Description:      "Extremely capable small language model. Strong at reasoning, coding, and math.",
			SizeBytes:        2_100_000_000,
			Parameters:       "3.8B",
			Tags:             []string{"Reasoning", "Coding", "Math"},
			DownloadURL:      "https://huggingface.co/microsoft/Phi-4-mini-instruct-gguf/resolve/main/Phi-4-mini-instruct-Q4_K_M.gguf",
			Filename:         "Phi-4-mini-instruct-Q4_K_M.gguf",
			ChecksumSHA256:   "",
			MinRamGB:         3.0,
			RecommendedRamGB: 5.0,
			Capabilities:     []string{"reasoning", "coding", "math", "logic"},
			SpeedClass:       SpeedFast,
		},
		{
			ID:               "llama-3.2-3b",
			Name:             "Llama 3.2 3B",
			Provider:         "Meta",
			Description:      "Optimized for mobile and edge devices. Well-balanced chat and general tasks.",
			SizeBytes:        2_500_000_000,
			Parameters:       "3B",
			Tags:             []string{"Balanced", "Chat", "General"},
			DownloadURL:      "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct-gguf/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
			Filename:         "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
			ChecksumSHA256:   "",
			MinRamGB:         4.0,
			RecommendedRamGB: 6.0,
			Capabilities:     []string{"chat", "general", "creative"},
			SpeedClass:       SpeedMedium,
		},
		{
			ID:               "qwen-2.5-3b",
			Name:             "Qwen 2.5 3B",
			Provider:         "Alibaba",
			Description:      "High performance multilingual model with strong coding abilities.",
			SizeBytes:        3_100_000_000,
			Parameters:       "3B",
			Tags:             []string{"Multilingual", "Coding"},
			DownloadURL:      "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-gguf/resolve/main/Qwen2.5-3B-Instruct-Q4_K_M.gguf",
			Filename:         "Qwen2.5-3B-Instruct-Q4_K_M.gguf",
			ChecksumSHA256:   "",
			MinRamGB:         4.0,
			RecommendedRamGB: 6.0,
			Capabilities:     []string{"multilingual", "coding", "translation"},
			SpeedClass:       SpeedMedium,
		},
	}
}
