// Ashwath Engine gRPC Service Definition
// Frontends communicate with the engine through this API.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AshwathEngine_Generate_FullMethodName      = "/ashwath.AshwathEngine/Generate"
	AshwathEngine_ListModels_FullMethodName    = "/ashwath.AshwathEngine/ListModels"
	AshwathEngine_InstallModel_FullMethodName  = "/ashwath.AshwathEngine/InstallModel"
	AshwathEngine_GetDeviceInfo_FullMethodName = "/ashwath.AshwathEngine/GetDeviceInfo"
	AshwathEngine_Shutdown_FullMethodName      = "/ashwath.AshwathEngine/Shutdown"
)

// AshwathEngineClient is the client API for AshwathEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AshwathEngineClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
	ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error)
	InstallModel(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error)
	GetDeviceInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceInfo, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type ashwathEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAshwathEngineClient(cc grpc.ClientConnInterface) AshwathEngineClient {
	return &ashwathEngineClient{cc}
}

func (c *ashwathEngineClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AshwathEngine_ServiceDesc.Streams[0], AshwathEngine_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AshwathEngine_GenerateClient = grpc.ServerStreamingClient[GenerateResponse]

func (c *ashwathEngineClient) ListModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelList)
	err := c.cc.Invoke(ctx, AshwathEngine_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ashwathEngineClient) InstallModel(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*InstallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallResponse)
	err := c.cc.Invoke(ctx, AshwathEngine_InstallModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ashwathEngineClient) GetDeviceInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceInfo)
	err := c.cc.Invoke(ctx, AshwathEngine_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ashwathEngineClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AshwathEngine_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AshwathEngineServer is the server API for AshwathEngine service.
// All implementations must embed UnimplementedAshwathEngineServer
// for forward compatibility.
type AshwathEngineServer interface {
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	ListModels(context.Context, *Empty) (*ModelList, error)
	InstallModel(context.Context, *InstallRequest) (*InstallResponse, error)
	GetDeviceInfo(context.Context, *Empty) (*DeviceInfo, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedAshwathEngineServer()
}

// UnimplementedAshwathEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAshwathEngineServer struct{}

func (UnimplementedAshwathEngineServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedAshwathEngineServer) ListModels(context.Context, *Empty) (*ModelList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAshwathEngineServer) InstallModel(context.Context, *InstallRequest) (*InstallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallModel not implemented")
}
func (UnimplementedAshwathEngineServer) GetDeviceInfo(context.Context, *Empty) (*DeviceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedAshwathEngineServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAshwathEngineServer) mustEmbedUnimplementedAshwathEngineServer() {}
func (UnimplementedAshwathEngineServer) testEmbeddedByValue()                       {}

// UnsafeAshwathEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AshwathEngineServer will
// result in compilation errors.
type UnsafeAshwathEngineServer interface {
	mustEmbedUnimplementedAshwathEngineServer()
}

func RegisterAshwathEngineServer(s grpc.ServiceRegistrar, srv AshwathEngineServer) {
	// If the following call panics, it indicates UnimplementedAshwathEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AshwathEngine_ServiceDesc, srv)
}

func _AshwathEngine_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AshwathEngineServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AshwathEngine_GenerateServer = grpc.ServerStreamingServer[GenerateResponse]

func _AshwathEngine_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AshwathEngineServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AshwathEngine_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AshwathEngineServer).ListModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AshwathEngine_InstallModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AshwathEngineServer).InstallModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AshwathEngine_InstallModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AshwathEngineServer).InstallModel(ctx, req.(*InstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AshwathEngine_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AshwathEngineServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AshwathEngine_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AshwathEngineServer).GetDeviceInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AshwathEngine_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AshwathEngineServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AshwathEngine_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AshwathEngineServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AshwathEngine_ServiceDesc is the grpc.ServiceDesc for AshwathEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AshwathEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ashwath.AshwathEngine",
	HandlerType: (*AshwathEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _AshwathEngine_ListModels_Handler,
		},
		{
			MethodName: "InstallModel",
			Handler:    _AshwathEngine_InstallModel_Handler,
		},
		{
			MethodName: "GetDeviceInfo",
			Handler:    _AshwathEngine_GetDeviceInfo_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _AshwathEngine_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _AshwathEngine_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
